
/* Populate Prereq table */
DELETE from dbo.prereq;

INSERT INTO dbo.prereq (course, prereq)
SELECT c.id, p.id FROM dbo.course c, dbo.course p
WHERE	(c.subject = 'ACCT' AND c.level = 161
AND		p.subject = 'ACCT' AND p.level = 111)
OR		(c.subject = 'ACCT' AND c.level = 162
AND		p.subject = 'ACCT' AND p.level = 111)
OR		(c.subject = 'ACCT' AND c.level = 164
AND		p.subject = 'ACCT' AND p.level = 111)
OR		(c.subject = 'ACCT' AND c.level = 214
AND		p.subject = 'ACCT' AND p.level = 161)
OR		(c.subject = 'ACCT' AND c.level = 214
AND		p.subject = 'ACCT' AND p.level = 164)
OR		(c.subject = 'ACCT' AND c.level = 215
AND		p.subject = 'MGMT' AND p.level = 107)
OR		(c.subject = 'ACCT' AND c.level = 218
AND		p.subject = 'ACCT' AND p.level = 111)
OR		(c.subject = 'ACCT' AND c.level = 268
AND		p.subject = 'ACCT' AND p.level = 322)
OR		(c.subject = 'ACCT' AND c.level = 275
AND		p.subject = 'MGMT' AND p.level = 107)
OR		(c.subject = 'ACCT' AND c.level = 275
AND		p.subject = 'ACCT' AND p.level = 315)
OR		(c.subject = 'ACCT' AND c.level = 311
AND		p.subject = 'ECON' AND p.level = 102)
OR		(c.subject = 'ACCT' AND c.level = 315
AND		p.subject = 'ACCT' AND p.level = 311)
OR		(c.subject = 'ACCT' AND c.level = 315
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'ACCT' AND c.level = 316
AND		p.subject = 'ACCT' AND p.level = 315)
OR		(c.subject = 'ACCT' AND c.level = 318
AND		p.subject = 'ACCT' AND p.level = 268)
OR		(c.subject = 'ACCT' AND c.level = 318
AND		p.subject = 'ACCT' AND p.level = 215)
OR		(c.subject = 'ACCT' AND c.level = 322
AND		p.subject = 'ACCT' AND p.level = 311)
OR		(c.subject = 'ACCT' AND c.level = 324
AND		p.subject = 'ACCT' AND p.level = 322)
OR		(c.subject = 'ACCT' AND c.level = 328
AND		p.subject = 'ACCT' AND p.level = 311)
OR		(c.subject = 'ACCT' AND c.level = 353
AND		p.subject = 'MGMT' AND p.level = 122)
OR		(c.subject = 'ACCT' AND c.level = 358
AND		p.subject = 'ACCT' AND p.level = 318)
OR		(c.subject = 'ACCT' AND c.level = 366
AND		p.subject = 'ACCT' AND p.level = 311)
OR		(c.subject = 'ACCT' AND c.level = 370
AND		p.subject = 'ACCT' AND p.level = 261)
OR		(c.subject = 'ACCT' AND c.level = 370
AND		p.subject = 'ACCT' AND p.level = 318)
OR		(c.subject = 'ACCT' AND c.level = 371
AND		p.subject = 'ACCT' AND p.level = 442)
OR		(c.subject = 'ACCT' AND c.level = 371
AND		p.subject = 'ACCT' AND p.level = 410)
OR		(c.subject = 'ACCT' AND c.level = 371
AND		p.subject = 'ACCT' AND p.level = 422)
OR		(c.subject = 'ACCT' AND c.level = 371
AND		p.subject = 'ACCT' AND p.level = 370)
OR		(c.subject = 'ACCT' AND c.level = 371
AND		p.subject = 'ACCT' AND p.level = 412)
OR		(c.subject = 'ACCT' AND c.level = 372
AND		p.subject = 'ACCT' AND p.level = 371)
OR		(c.subject = 'ACCT' AND c.level = 373
AND		p.subject = 'ACCT' AND p.level = 372)
OR		(c.subject = 'ACCT' AND c.level = 374
AND		p.subject = 'ACCT' AND p.level = 373)
OR		(c.subject = 'ACCT' AND c.level = 375
AND		p.subject = 'ACCT' AND p.level = 374)
OR		(c.subject = 'ACCT' AND c.level = 376
AND		p.subject = 'ACCT' AND p.level = 375)
OR		(c.subject = 'ACCT' AND c.level = 377
AND		p.subject = 'ACCT' AND p.level = 376)
OR		(c.subject = 'ACCT' AND c.level = 378
AND		p.subject = 'ACCT' AND p.level = 377)
OR		(c.subject = 'ACCT' AND c.level = 390
AND		p.subject = 'ACCT' AND p.level = 442)
OR		(c.subject = 'ACCT' AND c.level = 392
AND		p.subject = 'ACCT' AND p.level = 162)
OR		(c.subject = 'ACCT' AND c.level = 395
AND		p.subject = 'MGMT' AND p.level = 103)
OR		(c.subject = 'ACCT' AND c.level = 395
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'ACCT' AND c.level = 398
AND		p.subject = 'ACCT' AND p.level = 410)
OR		(c.subject = 'ACCT' AND c.level = 398
AND		p.subject = 'ACCT' AND p.level = 422)
OR		(c.subject = 'ACCT' AND c.level = 398
AND		p.subject = 'ACCT' AND p.level = 412)
OR		(c.subject = 'ACCT' AND c.level = 410
AND		p.subject = 'ACCT' AND p.level = 316)
OR		(c.subject = 'ACCT' AND c.level = 412
AND		p.subject = 'ACCT' AND p.level = 315)
OR		(c.subject = 'ACCT' AND c.level = 422
AND		p.subject = 'ACCT' AND p.level = 324)
OR		(c.subject = 'ACCT' AND c.level = 428
AND		p.subject = 'ACCT' AND p.level = 328)
OR		(c.subject = 'ACCT' AND c.level = 430
AND		p.subject = 'ACCT' AND p.level = 322)
OR		(c.subject = 'ACCT' AND c.level = 442
AND		p.subject = 'ACCT' AND p.level = 315)
OR		(c.subject = 'ACCT' AND c.level = 493
AND		p.subject = 'ACCT' AND p.level = 316)
OR		(c.subject = 'ACCT' AND c.level = 493
AND		p.subject = 'ACCT' AND p.level = 328)
OR		(c.subject = 'ACCT' AND c.level = 493
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'ACCT' AND c.level = 493
AND		p.subject = 'ACCT' AND p.level = 318)
/* BIOL */
OR		(c.subject = 'BIOL' AND c.level = 201
AND		p.subject = 'BIOL' AND p.level = 107)
OR		(c.subject = 'BIOL' AND c.level = 201
AND		p.subject = 'CHEM' AND p.level = 101)
OR		(c.subject = 'BIOL' AND c.level = 205
AND		p.subject = 'BIOL' AND p.level = 107)
OR		(c.subject = 'BIOL' AND c.level = 207
AND		p.subject = 'BIOL' AND p.level = 107)
OR		(c.subject = 'BIOL' AND c.level = 208
AND		p.subject = 'BIOL' AND p.level = 108)
OR		(c.subject = 'BIOL' AND c.level = 211
AND		p.subject = 'BIOL' AND p.level = 207)
OR		(c.subject = 'BIOL' AND c.level = 211
AND		p.subject = 'CHEM' AND p.level = 101)
OR		(c.subject = 'BIOL' AND c.level = 300
AND		p.subject = 'BIOL' AND p.level = 201)
OR		(c.subject = 'BIOL' AND c.level = 300
AND		p.subject = 'BIOL' AND p.level = 205)
OR		(c.subject = 'BIOL' AND c.level = 310
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 312
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 313
AND		p.subject = 'BIOL' AND p.level = 201)
OR		(c.subject = 'BIOL' AND c.level = 313
AND		p.subject = 'BIOL' AND p.level = 205)
OR		(c.subject = 'BIOL' AND c.level = 314
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 314
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'BIOL' AND c.level = 315
AND		p.subject = 'BIOL' AND p.level = 207)
OR		(c.subject = 'BIOL' AND c.level = 315
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 316
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 316
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'BIOL' AND c.level = 321
AND		p.subject = 'BIOL' AND p.level = 108)
OR		(c.subject = 'BIOL' AND c.level = 321
AND		p.subject = 'BIOL' AND p.level = 207)
OR		(c.subject = 'BIOL' AND c.level = 323
AND		p.subject = 'BIOL' AND p.level = 207)
OR		(c.subject = 'BIOL' AND c.level = 337
AND		p.subject = 'BIOL' AND p.level = 207)
OR		(c.subject = 'BIOL' AND c.level = 337
AND		p.subject = 'STAT' AND p.level = 151)
OR		(c.subject = 'BIOL' AND c.level = 361
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 365
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 367
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 371
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 385
AND		p.subject = 'BIOL' AND p.level = 207)
OR		(c.subject = 'BIOL' AND c.level = 410
AND		p.subject = 'BIOL' AND p.level = 310)
OR		(c.subject = 'BIOL' AND c.level = 410
AND		p.subject = 'BIOL' AND p.level = 312)
OR		(c.subject = 'BIOL' AND c.level = 413
AND		p.subject = 'BIOL' AND p.level = 313)
OR		(c.subject = 'BIOL' AND c.level = 414
AND		p.subject = 'BIOL' AND p.level = 310)
OR		(c.subject = 'BIOL' AND c.level = 414
AND		p.subject = 'BIOL' AND p.level = 312)
OR		(c.subject = 'BIOL' AND c.level = 421
AND		p.subject = 'BIOL' AND p.level = 205)
OR		(c.subject = 'BIOL' AND c.level = 421
AND		p.subject = 'BIOL' AND p.level = 310)
OR		(c.subject = 'BIOL' AND c.level = 421
AND		p.subject = 'BIOL' AND p.level = 320)
OR		(c.subject = 'BIOL' AND c.level = 422
AND		p.subject = 'BIOL' AND p.level = 208)
OR		(c.subject = 'BIOL' AND c.level = 422
AND		p.subject = 'BIOL' AND p.level = 337)
OR		(c.subject = 'BIOL' AND c.level = 422
AND		p.subject = 'BIOL' AND p.level = 310)
OR		(c.subject = 'BIOL' AND c.level = 430
AND		p.subject = 'BIOL' AND p.level = 300)
OR		(c.subject = 'BIOL' AND c.level = 492
AND		p.subject = 'BIOL' AND p.level = 300)
OR		(c.subject = 'BIOL' AND c.level = 495
AND		p.subject = 'BIOL' AND p.level = 300)
OR		(c.subject = 'BIOL' AND c.level = 498
AND		p.subject = 'BIOL' AND p.level = 300)
/* BUSN */
OR		(c.subject = 'BUSN' AND c.level = 312
AND		p.subject = 'BUSN' AND p.level = 201)
OR		(c.subject = 'BUSN' AND c.level = 330
AND		p.subject = 'BUSN' AND p.level = 201)
OR		(c.subject = 'BUSN' AND c.level = 350
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'BUSN' AND c.level = 396
AND		p.subject = 'MGTS' AND p.level = 312)
OR		(c.subject = 'BUSN' AND c.level = 397
AND		p.subject = 'ORGA' AND p.level = 201)
OR		(c.subject = 'BUSN' AND c.level = 401
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'BUSN' AND c.level = 401
AND		p.subject = 'ACCT' AND p.level = 322)
OR		(c.subject = 'BUSN' AND c.level = 450
AND		p.subject = 'ACCT' AND p.level = 322)
OR		(c.subject = 'BUSN' AND c.level = 450
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'BUSN' AND c.level = 450
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'BUSN' AND c.level = 496
AND		p.subject = 'BUSN' AND p.level = 396)
OR		(c.subject = 'BUSN' AND c.level = 496
AND		p.subject = 'BUSN' AND p.level = 397)
/* CHEM */
OR		(c.subject = 'CHEM' AND c.level = 102
AND		p.subject = 'CHEM' AND p.level = 101)
OR		(c.subject = 'CHEM' AND c.level = 211
AND		p.subject = 'CHEM' AND p.level = 102)
OR		(c.subject = 'CHEM' AND c.level = 232
AND		p.subject = 'CHEM' AND p.level = 102)
OR		(c.subject = 'CHEM' AND c.level = 242
AND		p.subject = 'CHEM' AND p.level = 102)
OR		(c.subject = 'CHEM' AND c.level = 242
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'CHEM' AND c.level = 261
AND		p.subject = 'CHEM' AND p.level = 102)
OR		(c.subject = 'CHEM' AND c.level = 263
AND		p.subject = 'CHEM' AND p.level = 261)
OR		(c.subject = 'CHEM' AND c.level = 311
AND		p.subject = 'CHEM' AND p.level = 211)
OR		(c.subject = 'CHEM' AND c.level = 320
AND		p.subject = 'EASC' AND p.level = 219)
OR		(c.subject = 'CHEM' AND c.level = 320
AND		p.subject = 'CHEM' AND p.level = 242)
OR		(c.subject = 'CHEM' AND c.level = 322
AND		p.subject = 'CHEM' AND p.level = 232)
OR		(c.subject = 'CHEM' AND c.level = 322
AND		p.subject = 'EASC' AND p.level = 226)
OR		(c.subject = 'CHEM' AND c.level = 333
AND		p.subject = 'CHEM' AND p.level = 232)
OR		(c.subject = 'CHEM' AND c.level = 342
AND		p.subject = 'CHEM' AND p.level = 242)
OR		(c.subject = 'CHEM' AND c.level = 342
AND		p.subject = 'PHYS' AND p.level = 224)
OR		(c.subject = 'CHEM' AND c.level = 353
AND		p.subject = 'CHEM' AND p.level = 261)
OR		(c.subject = 'CHEM' AND c.level = 353
AND		p.subject = 'CHEM' AND p.level = 211)
OR		(c.subject = 'CHEM' AND c.level = 362
AND		p.subject = 'CHEM' AND p.level = 263)
OR		(c.subject = 'CHEM' AND c.level = 364
AND		p.subject = 'CHEM' AND p.level = 263)
OR		(c.subject = 'CHEM' AND c.level = 372
AND		p.subject = 'CHEM' AND p.level = 102)
OR		(c.subject = 'CHEM' AND c.level = 372
AND		p.subject = 'CHEM' AND p.level = 261)
OR		(c.subject = 'CHEM' AND c.level = 380
AND		p.subject = 'CHEM' AND p.level = 211)
OR		(c.subject = 'CHEM' AND c.level = 380
AND		p.subject = 'CHEM' AND p.level = 263)
OR		(c.subject = 'CHEM' AND c.level = 391
AND		p.subject = 'CHEM' AND p.level = 261)
OR		(c.subject = 'CHEM' AND c.level = 410
AND		p.subject = 'CHEM' AND p.level = 311)
OR		(c.subject = 'CHEM' AND c.level = 441
AND		p.subject = 'CHEM' AND p.level = 342)
OR		(c.subject = 'CHEM' AND c.level = 442
AND		p.subject = 'CHEM' AND p.level = 342)
OR		(c.subject = 'CHEM' AND c.level = 464
AND		p.subject = 'CHEM' AND p.level = 364)
OR		(c.subject = 'CHEM' AND c.level = 466
AND		p.subject = 'CHEM' AND p.level = 333)
OR		(c.subject = 'CHEM' AND c.level = 472
AND		p.subject = 'CHEM' AND p.level = 261)
OR		(c.subject = 'CHEM' AND c.level = 472
AND		p.subject = 'CHEM' AND p.level = 372)
OR		(c.subject = 'CHEM' AND c.level = 474
AND		p.subject = 'CHEM' AND p.level = 311)
OR		(c.subject = 'CHEM' AND c.level = 474
AND		p.subject = 'CHEM' AND p.level = 372)
OR		(c.subject = 'CHEM' AND c.level = 484
AND		p.subject = 'CHEM' AND p.level = 311)
OR		(c.subject = 'CHEM' AND c.level = 495
AND		p.subject = 'CHEM' AND p.level = 311)
OR		(c.subject = 'CHEM' AND c.level = 496
AND		p.subject = 'CHEM' AND p.level = 311)
OR		(c.subject = 'CHEM' AND c.level = 497
AND		p.subject = 'CHEM' AND p.level = 311)
OR		(c.subject = 'CHEM' AND c.level = 497
AND		p.subject = 'CHEM' AND p.level = 320)
/* CMPT */
OR		(c.subject = 'CMPT' AND c.level = 103
AND		p.subject = 'CMPT' AND p.level = 101)
OR		(c.subject = 'CMPT' AND c.level = 200
AND		p.subject = 'CMPT' AND p.level = 103)
OR		(c.subject = 'CMPT' AND c.level = 201
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 204
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 204
AND		p.subject = 'CMPT' AND p.level = 272)
OR		(c.subject = 'CMPT' AND c.level = 204
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'CMPT' AND c.level = 220
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 229
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 230
AND		p.subject = 'CMPT' AND p.level = 101)
OR		(c.subject = 'CMPT' AND c.level = 250
AND		p.subject = 'CMPT' AND p.level = 101)
OR		(c.subject = 'CMPT' AND c.level = 272
AND		p.subject = 'CMPT' AND p.level = 101)
OR		(c.subject = 'CMPT' AND c.level = 272
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'CMPT' AND c.level = 272
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'CMPT' AND c.level = 280
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 291
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 305
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 306
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 306
AND		p.subject = 'CMPT' AND p.level = 272)
OR		(c.subject = 'CMPT' AND c.level = 310
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 311
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 315
AND		p.subject = 'CMPT' AND p.level = 291)
OR		(c.subject = 'CMPT' AND c.level = 315
AND		p.subject = 'CMPT' AND p.level = 305)
OR		(c.subject = 'CMPT' AND c.level = 330
AND		p.subject = 'CMPT' AND p.level = 305)
OR		(c.subject = 'CMPT' AND c.level = 330
AND		p.subject = 'CMPT' AND p.level = 230)
OR		(c.subject = 'CMPT' AND c.level = 340
AND		p.subject = 'CMPT' AND p.level = 200)
OR		(c.subject = 'CMPT' AND c.level = 340
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'CMPT' AND c.level = 340
AND		p.subject = 'MATH' AND p.level = 214)
OR		(c.subject = 'CMPT' AND c.level = 351
AND		p.subject = 'CMPT' AND p.level = 250)
OR		(c.subject = 'CMPT' AND c.level = 355
AND		p.subject = 'CMPT' AND p.level = 201)
OR		(c.subject = 'CMPT' AND c.level = 355
AND		p.subject = 'CMPT' AND p.level = 272)
OR		(c.subject = 'CMPT' AND c.level = 360
AND		p.subject = 'CMPT' AND p.level = 201)
OR		(c.subject = 'CMPT' AND c.level = 361
AND		p.subject = 'CMPT' AND p.level = 201)
OR		(c.subject = 'CMPT' AND c.level = 370
AND		p.subject = 'CMPT' AND p.level = 201)
OR		(c.subject = 'CMPT' AND c.level = 380
AND		p.subject = 'CMPT' AND p.level = 280)
OR		(c.subject = 'CMPT' AND c.level = 380
AND		p.subject = 'CMPT' AND p.level = 360)
OR		(c.subject = 'CMPT' AND c.level = 391
AND		p.subject = 'CMPT' AND p.level = 291)
OR		(c.subject = 'CMPT' AND c.level = 395
AND		p.subject = 'CMPT' AND p.level = 201)
OR		(c.subject = 'CMPT' AND c.level = 430
AND		p.subject = 'CMPT' AND p.level = 330)
OR		(c.subject = 'CMPT' AND c.level = 430
AND		p.subject = 'CMPT' AND p.level = 395)
OR		(c.subject = 'CMPT' AND c.level = 450
AND		p.subject = 'CMPT' AND p.level = 250)
OR		(c.subject = 'CMPT' AND c.level = 450
AND		p.subject = 'CMPT' AND p.level = 305)
OR		(c.subject = 'CMPT' AND c.level = 464
AND		p.subject = 'CMPT' AND p.level = 395)
OR		(c.subject = 'CMPT' AND c.level = 464
AND		p.subject = 'CMPT' AND p.level = 201)
OR		(c.subject = 'CMPT' AND c.level = 480
AND		p.subject = 'CMPT' AND p.level = 280)
OR		(c.subject = 'CMPT' AND c.level = 480
AND		p.subject = 'CMPT' AND p.level = 361)
OR		(c.subject = 'CMPT' AND c.level = 491
AND		p.subject = 'CMPT' AND p.level = 291)
OR		(c.subject = 'CMPT' AND c.level = 491
AND		p.subject = 'CMPT' AND p.level = 305)
OR		(c.subject = 'CMPT' AND c.level = 496
AND		p.subject = 'CMPT' AND p.level = 395)
/* DESN */
OR		(c.subject = 'DESN' AND c.level = 103
AND		p.subject = 'DESN' AND p.level = 102)
OR		(c.subject = 'DESN' AND c.level = 131
AND		p.subject = 'DESN' AND p.level = 110)
OR		(c.subject = 'DESN' AND c.level = 131
AND		p.subject = 'DESN' AND p.level = 120)
OR		(c.subject = 'DESN' AND c.level = 200
AND		p.subject = 'DESN' AND p.level = 203)
OR		(c.subject = 'DESN' AND c.level = 205
AND		p.subject = 'DESN' AND p.level = 110)
OR		(c.subject = 'DESN' AND c.level = 205
AND		p.subject = 'DESN' AND p.level = 120)
OR		(c.subject = 'DESN' AND c.level = 205
AND		p.subject = 'DESN' AND p.level = 150)
OR		(c.subject = 'DESN' AND c.level = 210
AND		p.subject = 'DESN' AND p.level = 102)
OR		(c.subject = 'DESN' AND c.level = 210
AND		p.subject = 'DESN' AND p.level = 110)
OR		(c.subject = 'DESN' AND c.level = 210
AND		p.subject = 'DESN' AND p.level = 120)
OR		(c.subject = 'DESN' AND c.level = 210
AND		p.subject = 'DESN' AND p.level = 150)
OR		(c.subject = 'DESN' AND c.level = 220
AND		p.subject = 'DESN' AND p.level = 120)
OR		(c.subject = 'DESN' AND c.level = 230
AND		p.subject = 'DESN' AND p.level = 102)
OR		(c.subject = 'DESN' AND c.level = 230
AND		p.subject = 'DESN' AND p.level = 110)
OR		(c.subject = 'DESN' AND c.level = 230
AND		p.subject = 'DESN' AND p.level = 120)
OR		(c.subject = 'DESN' AND c.level = 231
AND		p.subject = 'DESN' AND p.level = 131)
OR		(c.subject = 'DESN' AND c.level = 240
AND		p.subject = 'DESN' AND p.level = 205)
OR		(c.subject = 'DESN' AND c.level = 240
AND		p.subject = 'DESN' AND p.level = 131)
OR		(c.subject = 'DESN' AND c.level = 241
AND		p.subject = 'DESN' AND p.level = 240)
OR		(c.subject = 'DESN' AND c.level = 250
AND		p.subject = 'DESN' AND p.level = 120)
OR		(c.subject = 'DESN' AND c.level = 250
AND		p.subject = 'DESN' AND p.level = 150)
OR		(c.subject = 'DESN' AND c.level = 251
AND		p.subject = 'DESN' AND p.level = 250)
OR		(c.subject = 'DESN' AND c.level = 252
AND		p.subject = 'DESN' AND p.level = 120)
OR		(c.subject = 'DESN' AND c.level = 261
AND		p.subject = 'DESN' AND p.level = 131)
OR		(c.subject = 'DESN' AND c.level = 261
AND		p.subject = 'DESN' AND p.level = 260)
OR		(c.subject = 'DESN' AND c.level = 270
AND		p.subject = 'ENGL' AND p.level = 102)
OR		(c.subject = 'DESN' AND c.level = 271
AND		p.subject = 'DESN' AND p.level = 270)
OR		(c.subject = 'DESN' AND c.level = 290
AND		p.subject = 'DESN' AND p.level = 220)
OR		(c.subject = 'DESN' AND c.level = 290
AND		p.subject = 'DESN' AND p.level = 240)
OR		(c.subject = 'DESN' AND c.level = 290
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 295
AND		p.subject = 'DESN' AND p.level = 231)
OR		(c.subject = 'DESN' AND c.level = 295
AND		p.subject = 'DESN' AND p.level = 240)
OR		(c.subject = 'DESN' AND c.level = 295
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 300
AND		p.subject = 'DESN' AND p.level = 200)
OR		(c.subject = 'DESN' AND c.level = 310
AND		p.subject = 'DESN' AND p.level = 205)
OR		(c.subject = 'DESN' AND c.level = 311
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 311
AND		p.subject = 'DESN' AND p.level = 231)
OR		(c.subject = 'DESN' AND c.level = 313
AND		p.subject = 'DESN' AND p.level = 231)
OR		(c.subject = 'DESN' AND c.level = 314
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 315
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 316
AND		p.subject = 'DESN' AND p.level = 311)
OR		(c.subject = 'DESN' AND c.level = 317
AND		p.subject = 'DESN' AND p.level = 220)
OR		(c.subject = 'DESN' AND c.level = 317
AND		p.subject = 'DESN' AND p.level = 231)
OR		(c.subject = 'DESN' AND c.level = 317
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 318
AND		p.subject = 'DESN' AND p.level = 311)
OR		(c.subject = 'DESN' AND c.level = 330
AND		p.subject = 'DESN' AND p.level = 230)
OR		(c.subject = 'DESN' AND c.level = 331
AND		p.subject = 'DESN' AND p.level = 231)
OR		(c.subject = 'DESN' AND c.level = 340
AND		p.subject = 'DESN' AND p.level = 240)
OR		(c.subject = 'DESN' AND c.level = 341
AND		p.subject = 'DESN' AND p.level = 241)
OR		(c.subject = 'DESN' AND c.level = 342
AND		p.subject = 'DESN' AND p.level = 240)
OR		(c.subject = 'DESN' AND c.level = 343
AND		p.subject = 'DESN' AND p.level = 340)
OR		(c.subject = 'DESN' AND c.level = 344
AND		p.subject = 'DESN' AND p.level = 131)
OR		(c.subject = 'DESN' AND c.level = 344
AND		p.subject = 'DESN' AND p.level = 205)
OR		(c.subject = 'DESN' AND c.level = 344
AND		p.subject = 'DESN' AND p.level = 240)
OR		(c.subject = 'DESN' AND c.level = 350
AND		p.subject = 'DESN' AND p.level = 250)
OR		(c.subject = 'DESN' AND c.level = 352
AND		p.subject = 'DESN' AND p.level = 250)
OR		(c.subject = 'DESN' AND c.level = 361
AND		p.subject = 'DESN' AND p.level = 261)
OR		(c.subject = 'DESN' AND c.level = 380
AND		p.subject = 'DESN' AND p.level = 205)
OR		(c.subject = 'DESN' AND c.level = 381
AND		p.subject = 'DESN' AND p.level = 271)
OR		(c.subject = 'DESN' AND c.level = 390
AND		p.subject = 'DESN' AND p.level = 300)
OR		(c.subject = 'DESN' AND c.level = 390
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 390
AND		p.subject = 'DESN' AND p.level = 311)
OR		(c.subject = 'DESN' AND c.level = 390
AND		p.subject = 'DESN' AND p.level = 313)
OR		(c.subject = 'DESN' AND c.level = 390
AND		p.subject = 'DESN' AND p.level = 314)
OR		(c.subject = 'DESN' AND c.level = 391
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 391
AND		p.subject = 'DESN' AND p.level = 311)
OR		(c.subject = 'DESN' AND c.level = 393
AND		p.subject = 'DESN' AND p.level = 240)
OR		(c.subject = 'DESN' AND c.level = 393
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 393
AND		p.subject = 'DESN' AND p.level = 311)
OR		(c.subject = 'DESN' AND c.level = 395
AND		p.subject = 'DESN' AND p.level = 290)
OR		(c.subject = 'DESN' AND c.level = 395
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 395
AND		p.subject = 'DESN' AND p.level = 311)
OR		(c.subject = 'DESN' AND c.level = 400
AND		p.subject = 'DESN' AND p.level = 300)
OR		(c.subject = 'DESN' AND c.level = 410
AND		p.subject = 'DESN' AND p.level = 271)
OR		(c.subject = 'DESN' AND c.level = 410
AND		p.subject = 'DESN' AND p.level = 311)
OR		(c.subject = 'DESN' AND c.level = 410
AND		p.subject = 'DESN' AND p.level = 380)
OR		(c.subject = 'DESN' AND c.level = 413
AND		p.subject = 'DESN' AND p.level = 313)
OR		(c.subject = 'DESN' AND c.level = 414
AND		p.subject = 'DESN' AND p.level = 314)
OR		(c.subject = 'DESN' AND c.level = 415
AND		p.subject = 'DESN' AND p.level = 410)
OR		(c.subject = 'DESN' AND c.level = 417
AND		p.subject = 'DESN' AND p.level = 317)
OR		(c.subject = 'DESN' AND c.level = 418
AND		p.subject = 'DESN' AND p.level = 318)
OR		(c.subject = 'DESN' AND c.level = 440
AND		p.subject = 'DESN' AND p.level = 340)
OR		(c.subject = 'DESN' AND c.level = 442
AND		p.subject = 'DESN' AND p.level = 342)
OR		(c.subject = 'DESN' AND c.level = 443
AND		p.subject = 'DESN' AND p.level = 342)
OR		(c.subject = 'DESN' AND c.level = 443
AND		p.subject = 'DESN' AND p.level = 344)
OR		(c.subject = 'DESN' AND c.level = 444
AND		p.subject = 'DESN' AND p.level = 344)
OR		(c.subject = 'DESN' AND c.level = 445
AND		p.subject = 'DESN' AND p.level = 440)
OR		(c.subject = 'DESN' AND c.level = 445
AND		p.subject = 'DESN' AND p.level = 443)
OR		(c.subject = 'DESN' AND c.level = 445
AND		p.subject = 'DESN' AND p.level = 444)
OR		(c.subject = 'DESN' AND c.level = 480
AND		p.subject = 'DESN' AND p.level = 271)
OR		(c.subject = 'DESN' AND c.level = 485
AND		p.subject = 'DESN' AND p.level = 240)
OR		(c.subject = 'DESN' AND c.level = 485
AND		p.subject = 'DESN' AND p.level = 310)
OR		(c.subject = 'DESN' AND c.level = 485
AND		p.subject = 'DESN' AND p.level = 380)
OR		(c.subject = 'DESN' AND c.level = 486
AND		p.subject = 'DESN' AND p.level = 380)
/* EASC */
OR		(c.subject = 'EASC' AND c.level = 206
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 209
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 219
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 221
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 225
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 226
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 230
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 238
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 240
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 240
AND		p.subject = 'EASC' AND p.level = 102)
OR		(c.subject = 'EASC' AND c.level = 270
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'EASC' AND c.level = 271
AND		p.subject = 'EASC' AND p.level = 102)
OR		(c.subject = 'EASC' AND c.level = 320
AND		p.subject = 'EASC' AND p.level = 219)
OR		(c.subject = 'EASC' AND c.level = 320
AND		p.subject = 'CHEM' AND p.level = 242)
OR		(c.subject = 'EASC' AND c.level = 321
AND		p.subject = 'EASC' AND p.level = 225)
OR		(c.subject = 'EASC' AND c.level = 321
AND		p.subject = 'PHYS' AND p.level = 124)
OR		(c.subject = 'EASC' AND c.level = 322
AND		p.subject = 'CHEM' AND p.level = 232)
OR		(c.subject = 'EASC' AND c.level = 322
AND		p.subject = 'EASC' AND p.level = 226)
OR		(c.subject = 'EASC' AND c.level = 324
AND		p.subject = 'EASC' AND p.level = 225)
OR		(c.subject = 'EASC' AND c.level = 330
AND		p.subject = 'EASC' AND p.level = 219)
OR		(c.subject = 'EASC' AND c.level = 334
AND		p.subject = 'EASC' AND p.level = 221)
OR		(c.subject = 'EASC' AND c.level = 373
AND		p.subject = 'EASC' AND p.level = 270)
OR		(c.subject = 'EASC' AND c.level = 375
AND		p.subject = 'EASC' AND p.level = 324)
OR		(c.subject = 'EASC' AND c.level = 406
AND		p.subject = 'EASC' AND p.level = 219)
OR		(c.subject = 'EASC' AND c.level = 406
AND		p.subject = 'EASC' AND p.level = 206)
OR		(c.subject = 'EASC' AND c.level = 406
AND		p.subject = 'EASC' AND p.level = 320)
OR		(c.subject = 'EASC' AND c.level = 495
AND		p.subject = 'EASC' AND p.level = 320)
/* ECON */
OR		(c.subject = 'ECON' AND c.level = 212
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 212
AND		p.subject = 'ECON' AND p.level = 102)
OR		(c.subject = 'ECON' AND c.level = 213
AND		p.subject = 'ECON' AND p.level = 102)
OR		(c.subject = 'ECON' AND c.level = 281
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 282
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 282
AND		p.subject = 'ECON' AND p.level = 102)
OR		(c.subject = 'ECON' AND c.level = 289
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 290
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 290
AND		p.subject = 'ECON' AND p.level = 102)
OR		(c.subject = 'ECON' AND c.level = 299
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 299
AND		p.subject = 'STAT' AND p.level = 151)
OR		(c.subject = 'ECON' AND c.level = 319
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 319
AND		p.subject = 'ECON' AND p.level = 102)
OR		(c.subject = 'ECON' AND c.level = 323
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 335
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 341
AND		p.subject = 'ECON' AND p.level = 102)
OR		(c.subject = 'ECON' AND c.level = 350
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 353
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 355
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 357
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 365
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 366
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 369
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'ECON' AND c.level = 373
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 373
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'ECON' AND c.level = 384
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 384
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'ECON' AND c.level = 385
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 385
AND		p.subject = 'ECON' AND p.level = 282)
OR		(c.subject = 'ECON' AND c.level = 389
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 389
AND		p.subject = 'ECON' AND p.level = 282)
OR		(c.subject = 'ECON' AND c.level = 389
AND		p.subject = 'ECON' AND p.level = 289)
OR		(c.subject = 'ECON' AND c.level = 399
AND		p.subject = 'ECON' AND p.level = 299)
OR		(c.subject = 'ECON' AND c.level = 401
AND		p.subject = 'ECON' AND p.level = 299)
OR		(c.subject = 'ECON' AND c.level = 414
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 414
AND		p.subject = 'ECON' AND p.level = 282)
OR		(c.subject = 'ECON' AND c.level = 421
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 421
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'ECON' AND c.level = 422
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 422
AND		p.subject = 'ECON' AND p.level = 282)
OR		(c.subject = 'ECON' AND c.level = 422
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'ECON' AND c.level = 441
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 441
AND		p.subject = 'ECON' AND p.level = 282)
OR		(c.subject = 'ECON' AND c.level = 441
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'ECON' AND c.level = 442
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 442
AND		p.subject = 'STAT' AND p.level = 151)
OR		(c.subject = 'ECON' AND c.level = 442
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'ECON' AND c.level = 467
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 467
AND		p.subject = 'ECON' AND p.level = 365)
OR		(c.subject = 'ECON' AND c.level = 467
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'ECON' AND c.level = 481
AND		p.subject = 'ECON' AND p.level = 384)
OR		(c.subject = 'ECON' AND c.level = 481
AND		p.subject = 'ECON' AND p.level = 389)
OR		(c.subject = 'ECON' AND c.level = 482
AND		p.subject = 'ECON' AND p.level = 384)
OR		(c.subject = 'ECON' AND c.level = 482
AND		p.subject = 'ECON' AND p.level = 385)
OR		(c.subject = 'ECON' AND c.level = 489
AND		p.subject = 'ECON' AND p.level = 389)
OR		(c.subject = 'ECON' AND c.level = 495
AND		p.subject = 'ECON' AND p.level = 399)
OR		(c.subject = 'ECON' AND c.level = 497
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 497
AND		p.subject = 'ECON' AND p.level = 282)
OR		(c.subject = 'ECON' AND c.level = 497
AND		p.subject = 'ECON' AND p.level = 399)
OR		(c.subject = 'ECON' AND c.level = 498
AND		p.subject = 'ECON' AND p.level = 281)
OR		(c.subject = 'ECON' AND c.level = 498
AND		p.subject = 'ECON' AND p.level = 282)
OR		(c.subject = 'ECON' AND c.level = 498
AND		p.subject = 'ECON' AND p.level = 299)
/* ENGL */
OR		(c.subject = 'ENGL' AND c.level = 103
AND		p.subject = 'ENGL' AND p.level = 102)
OR		(c.subject = 'ENGL' AND c.level = 205
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 205
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 207
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 207
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 211
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 215
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 218
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 218
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 219
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 219
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 240
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 240
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 243
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 282
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 282
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 283
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 283
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 284
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 284
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 285
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 285
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 286
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 286
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 288
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 297
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 297
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 307
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 307
AND		p.subject = 'ENGL' AND p.level = 133)
OR		(c.subject = 'ENGL' AND c.level = 319
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 320
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 324
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 337
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 340
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 341
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 342
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 348
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 350
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 352
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 353
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 358
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 361
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 362
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 364
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 365
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 366
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 368
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 374
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 376
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 377
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 381
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 382
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 383
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 388
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 389
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'ENGL' AND c.level = 391
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 391
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 401
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 401
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 401
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 401
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 402
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 402
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 402
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 402
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 405
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 405
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 405
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 405
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 481
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 481
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 481
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 481
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 489
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 489
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 489
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 489
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 491
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 491
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 491
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 491
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 492
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 492
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 492
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 492
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 493
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 493
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 493
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 493
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 494
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 494
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 494
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 494
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 495
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 495
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 495
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 495
AND		p.subject = 'ENGL' AND p.level = 215)
OR		(c.subject = 'ENGL' AND c.level = 496
AND		p.subject = 'ENGL' AND p.level = 267)
OR		(c.subject = 'ENGL' AND c.level = 496
AND		p.subject = 'ENGL' AND p.level = 391)
OR		(c.subject = 'ENGL' AND c.level = 496
AND		p.subject = 'ENGL' AND p.level = 392)
OR		(c.subject = 'ENGL' AND c.level = 496
AND		p.subject = 'ENGL' AND p.level = 393)
OR		(c.subject = 'ENGL' AND c.level = 497
AND		p.subject = 'ENGL' AND p.level = 205)
OR		(c.subject = 'ENGL' AND c.level = 497
AND		p.subject = 'ENGL' AND p.level = 207)
OR		(c.subject = 'ENGL' AND c.level = 497
AND		p.subject = 'ENGL' AND p.level = 211)
OR		(c.subject = 'ENGL' AND c.level = 497
AND		p.subject = 'ENGL' AND p.level = 215)
/* FNCE */
OR		(c.subject = 'FNCE' AND c.level = 301
AND		p.subject = 'ACCT' AND p.level = 311)
OR		(c.subject = 'FNCE' AND c.level = 301
AND		p.subject = 'FNCE' AND p.level = 113)
OR		(c.subject = 'FNCE' AND c.level = 303
AND		p.subject = 'FNCE' AND p.level = 113)
OR		(c.subject = 'FNCE' AND c.level = 401
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'FNCE' AND c.level = 401
AND		p.subject = 'ACCT' AND p.level = 322)
OR		(c.subject = 'FNCE' AND c.level = 404
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'FNCE' AND c.level = 406
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'FNCE' AND c.level = 406
AND		p.subject = 'ACCT' AND p.level = 322)
/* HIST */
OR		(c.subject = 'HIST' AND c.level = 300
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 300
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 300
AND		p.subject = 'HIST' AND p.level = 205)
OR		(c.subject = 'HIST' AND c.level = 301
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 304
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 306
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 308
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 309
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 311
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 315
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 338
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 340
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 341
AND		p.subject = 'HIST' AND p.level = 102)
OR		(c.subject = 'HIST' AND c.level = 342
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 345
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 352
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 361
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 362
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 366
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 367
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 369
AND		p.subject = 'HIST' AND p.level = 260)
OR		(c.subject = 'HIST' AND c.level = 397
AND		p.subject = 'HIST' AND p.level = 100)
OR		(c.subject = 'HIST' AND c.level = 410
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 410
AND		p.subject = 'HIST' AND p.level = 205)
OR		(c.subject = 'HIST' AND c.level = 410
AND		p.subject = 'HIST' AND p.level = 209)
OR		(c.subject = 'HIST' AND c.level = 411
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 411
AND		p.subject = 'HIST' AND p.level = 205)
OR		(c.subject = 'HIST' AND c.level = 411
AND		p.subject = 'HIST' AND p.level = 209)
OR		(c.subject = 'HIST' AND c.level = 442
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 442
AND		p.subject = 'HIST' AND p.level = 205)
OR		(c.subject = 'HIST' AND c.level = 442
AND		p.subject = 'HIST' AND p.level = 209)
OR		(c.subject = 'HIST' AND c.level = 460
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 460
AND		p.subject = 'HIST' AND p.level = 205)
OR		(c.subject = 'HIST' AND c.level = 460
AND		p.subject = 'HIST' AND p.level = 260)
OR		(c.subject = 'HIST' AND c.level = 476
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 476
AND		p.subject = 'HIST' AND p.level = 205)
OR		(c.subject = 'HIST' AND c.level = 490
AND		p.subject = 'HIST' AND p.level = 204)
OR		(c.subject = 'HIST' AND c.level = 490
AND		p.subject = 'HIST' AND p.level = 205)
OR		(c.subject = 'HIST' AND c.level = 490
AND		p.subject = 'HIST' AND p.level = 209)
OR		(c.subject = 'HIST' AND c.level = 499
AND		p.subject = 'HIST' AND p.level = 300)
/* MARK */
OR		(c.subject = 'MARK' AND c.level = 301
AND		p.subject = 'BUSN' AND p.level = 201)
OR		(c.subject = 'MARK' AND c.level = 301
AND		p.subject = 'ECON' AND p.level = 101)
OR		(c.subject = 'MARK' AND c.level = 310
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 312
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 312
AND		p.subject = 'BUSN' AND p.level = 201)
OR		(c.subject = 'MARK' AND c.level = 314
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 314
AND		p.subject = 'FNCE' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 324
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 403
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 412
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 414
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 416
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 418
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 420
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 440
AND		p.subject = 'MARK' AND p.level = 310)
OR		(c.subject = 'MARK' AND c.level = 440
AND		p.subject = 'MARK' AND p.level = 312)
OR		(c.subject = 'MARK' AND c.level = 440
AND		p.subject = 'MARK' AND p.level = 314)
OR		(c.subject = 'MARK' AND c.level = 497
AND		p.subject = 'MARK' AND p.level = 301)
OR		(c.subject = 'MARK' AND c.level = 499
AND		p.subject = 'BUSN' AND p.level = 496)
/* MATH */
OR		(c.subject = 'MATH' AND c.level = 101
AND		p.subject = 'MATH' AND p.level = 100)
OR		(c.subject = 'MATH' AND c.level = 102
AND		p.subject = 'MATH' AND p.level = 100)
OR		(c.subject = 'MATH' AND c.level = 115
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'MATH' AND c.level = 200
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'MATH' AND c.level = 214
AND		p.subject = 'MATH' AND p.level = 115)
OR		(c.subject = 'MATH' AND c.level = 214
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'MATH' AND c.level = 215
AND		p.subject = 'MATH' AND p.level = 214)
OR		(c.subject = 'MATH' AND c.level = 222
AND		p.subject = 'MATH' AND p.level = 100)
OR		(c.subject = 'MATH' AND c.level = 225
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'MATH' AND c.level = 228
AND		p.subject = 'MATH' AND p.level = 200)
OR		(c.subject = 'MATH' AND c.level = 228
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'MATH' AND c.level = 241
AND		p.subject = 'MATH' AND p.level = 100)
OR		(c.subject = 'MATH' AND c.level = 260
AND		p.subject = 'MATH' AND p.level = 160)
OR		(c.subject = 'MATH' AND c.level = 310
AND		p.subject = 'MATH' AND p.level = 214)
OR		(c.subject = 'MATH' AND c.level = 310
AND		p.subject = 'MATH' AND p.level = 200)
OR		(c.subject = 'MATH' AND c.level = 311
AND		p.subject = 'MATH' AND p.level = 215)
OR		(c.subject = 'MATH' AND c.level = 312
AND		p.subject = 'MATH' AND p.level = 215)
OR		(c.subject = 'MATH' AND c.level = 312
AND		p.subject = 'STAT' AND p.level = 265)
OR		(c.subject = 'MATH' AND c.level = 312
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'MATH' AND c.level = 320
AND		p.subject = 'MATH' AND p.level = 200)
OR		(c.subject = 'MATH' AND c.level = 321
AND		p.subject = 'MATH' AND p.level = 225)
OR		(c.subject = 'MATH' AND c.level = 321
AND		p.subject = 'MATH' AND p.level = 228)
OR		(c.subject = 'MATH' AND c.level = 330
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'MATH' AND c.level = 330
AND		p.subject = 'MATH' AND p.level = 214)
OR		(c.subject = 'MATH' AND c.level = 335
AND		p.subject = 'MATH' AND p.level = 214)
OR		(c.subject = 'MATH' AND c.level = 335
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'MATH' AND c.level = 341
AND		p.subject = 'MATH' AND p.level = 241)
OR		(c.subject = 'MATH' AND c.level = 341
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'MATH' AND c.level = 350
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'MATH' AND c.level = 350
AND		p.subject = 'MATH' AND p.level = 200)
OR		(c.subject = 'MATH' AND c.level = 361
AND		p.subject = 'MATH' AND p.level = 200)
OR		(c.subject = 'MATH' AND c.level = 410
AND		p.subject = 'MATH' AND p.level = 225)
OR		(c.subject = 'MATH' AND c.level = 410
AND		p.subject = 'MATH' AND p.level = 310)
OR		(c.subject = 'MATH' AND c.level = 420
AND		p.subject = 'MATH' AND p.level = 321)
OR		(c.subject = 'MATH' AND c.level = 430
AND		p.subject = 'MATH' AND p.level = 310)
OR		(c.subject = 'MATH' AND c.level = 430
AND		p.subject = 'MATH' AND p.level = 330)
OR		(c.subject = 'MATH' AND c.level = 436
AND		p.subject = 'MATH' AND p.level = 310)
OR		(c.subject = 'MATH' AND c.level = 436
AND		p.subject = 'MATH' AND p.level = 330)
OR		(c.subject = 'MATH' AND c.level = 495
AND		p.subject = 'MATH' AND p.level = 310)
/* MGMT */
OR		(c.subject = 'MGMT' AND c.level = 126
AND		p.subject = 'MGMT' AND p.level = 122)
OR		(c.subject = 'MGMT' AND c.level = 211
AND		p.subject = 'ACCT' AND p.level = 111)
OR		(c.subject = 'MGMT' AND c.level = 211
AND		p.subject = 'FNCE' AND p.level = 113)
OR		(c.subject = 'MGMT' AND c.level = 232
AND		p.subject = 'ACCT' AND p.level = 218)
OR		(c.subject = 'MGMT' AND c.level = 232
AND		p.subject = 'MGMT' AND p.level = 131)
OR		(c.subject = 'MGMT' AND c.level = 240
AND		p.subject = 'MGMT' AND p.level = 121)
OR		(c.subject = 'MGMT' AND c.level = 261
AND		p.subject = 'MGMT' AND p.level = 211)
OR		(c.subject = 'MGMT' AND c.level = 261
AND		p.subject = 'MGMT' AND p.level = 240)
OR		(c.subject = 'MGMT' AND c.level = 312
AND		p.subject = 'FNCE' AND p.level = 113)
OR		(c.subject = 'MGMT' AND c.level = 312
AND		p.subject = 'ACCT' AND p.level = 218)
OR		(c.subject = 'MGMT' AND c.level = 312
AND		p.subject = 'MGMT' AND p.level = 121)
OR		(c.subject = 'MGMT' AND c.level = 312
AND		p.subject = 'MGMT' AND p.level = 122)
OR		(c.subject = 'MGMT' AND c.level = 312
AND		p.subject = 'MGMT' AND p.level = 131)
/* MGTS */
OR		(c.subject = 'MGTS' AND c.level = 312
AND		p.subject = 'STAT' AND p.level = 151)
/* MUSC */
OR		(c.subject = 'MUSC' AND c.level = 104
AND		p.subject = 'MUSC' AND p.level = 103)
OR		(c.subject = 'MUSC' AND c.level = 112
AND		p.subject = 'MUSC' AND p.level = 111)
OR		(c.subject = 'MUSC' AND c.level = 124
AND		p.subject = 'MUSC' AND p.level = 123)
OR		(c.subject = 'MUSC' AND c.level = 132
AND		p.subject = 'MUSC' AND p.level = 131)
OR		(c.subject = 'MUSC' AND c.level = 142
AND		p.subject = 'MUSC' AND p.level = 141)
OR		(c.subject = 'MUSC' AND c.level = 189
AND		p.subject = 'MUSC' AND p.level = 188)
OR		(c.subject = 'MUSC' AND c.level = 201
AND		p.subject = 'MUSC' AND p.level = 104)
OR		(c.subject = 'MUSC' AND c.level = 202
AND		p.subject = 'MUSC' AND p.level = 201)
OR		(c.subject = 'MUSC' AND c.level = 207
AND		p.subject = 'MUSC' AND p.level = 104)
OR		(c.subject = 'MUSC' AND c.level = 208
AND		p.subject = 'MUSC' AND p.level = 104)
OR		(c.subject = 'MUSC' AND c.level = 211
AND		p.subject = 'MUSC' AND p.level = 104)
OR		(c.subject = 'MUSC' AND c.level = 212
AND		p.subject = 'MUSC' AND p.level = 211)
OR		(c.subject = 'MUSC' AND c.level = 213
AND		p.subject = 'MUSC' AND p.level = 112)
OR		(c.subject = 'MUSC' AND c.level = 214
AND		p.subject = 'MUSC' AND p.level = 213)
OR		(c.subject = 'MUSC' AND c.level = 215
AND		p.subject = 'MUSC' AND p.level = 132)
OR		(c.subject = 'MUSC' AND c.level = 215
AND		p.subject = 'MUSC' AND p.level = 104)
OR		(c.subject = 'MUSC' AND c.level = 216
AND		p.subject = 'MUSC' AND p.level = 215)
OR		(c.subject = 'MUSC' AND c.level = 217
AND		p.subject = 'MUSC' AND p.level = 132)
OR		(c.subject = 'MUSC' AND c.level = 218
AND		p.subject = 'MUSC' AND p.level = 217)
OR		(c.subject = 'MUSC' AND c.level = 219
AND		p.subject = 'MUSC' AND p.level = 213)
OR		(c.subject = 'MUSC' AND c.level = 221
AND		p.subject = 'MUSC' AND p.level = 132)
OR		(c.subject = 'MUSC' AND c.level = 222
AND		p.subject = 'MUSC' AND p.level = 221)
OR		(c.subject = 'MUSC' AND c.level = 233
AND		p.subject = 'MUSC' AND p.level = 132)
OR		(c.subject = 'MUSC' AND c.level = 235
AND		p.subject = 'MUSC' AND p.level = 233)
OR		(c.subject = 'MUSC' AND c.level = 243
AND		p.subject = 'MUSC' AND p.level = 132)
OR		(c.subject = 'MUSC' AND c.level = 243
AND		p.subject = 'MUSC' AND p.level = 142)
OR		(c.subject = 'MUSC' AND c.level = 244
AND		p.subject = 'MUSC' AND p.level = 243)
OR		(c.subject = 'MUSC' AND c.level = 253
AND		p.subject = 'MUSC' AND p.level = 132)
OR		(c.subject = 'MUSC' AND c.level = 253
AND		p.subject = 'MUSC' AND p.level = 142)
OR		(c.subject = 'MUSC' AND c.level = 254
AND		p.subject = 'MUSC' AND p.level = 253)
OR		(c.subject = 'MUSC' AND c.level = 263
AND		p.subject = 'MUSC' AND p.level = 104)
OR		(c.subject = 'MUSC' AND c.level = 294
AND		p.subject = 'MUSC' AND p.level = 189)
OR		(c.subject = 'MUSC' AND c.level = 295
AND		p.subject = 'MUSC' AND p.level = 294)
OR		(c.subject = 'MUSC' AND c.level = 301
AND		p.subject = 'ENGL' AND p.level = 102)
OR		(c.subject = 'MUSC' AND c.level = 301
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'MUSC' AND c.level = 301
AND		p.subject = 'MUSC' AND p.level = 123)
OR		(c.subject = 'MUSC' AND c.level = 301
AND		p.subject = 'MUSC' AND p.level = 124)
OR		(c.subject = 'MUSC' AND c.level = 302
AND		p.subject = 'ENGL' AND p.level = 102)
OR		(c.subject = 'MUSC' AND c.level = 302
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'MUSC' AND c.level = 302
AND		p.subject = 'MUSC' AND p.level = 123)
OR		(c.subject = 'MUSC' AND c.level = 302
AND		p.subject = 'MUSC' AND p.level = 124)
OR		(c.subject = 'MUSC' AND c.level = 303
AND		p.subject = 'ENGL' AND p.level = 102)
OR		(c.subject = 'MUSC' AND c.level = 303
AND		p.subject = 'ENGL' AND p.level = 103)
OR		(c.subject = 'MUSC' AND c.level = 303
AND		p.subject = 'MUSC' AND p.level = 123)
OR		(c.subject = 'MUSC' AND c.level = 303
AND		p.subject = 'MUSC' AND p.level = 124)
OR		(c.subject = 'MUSC' AND c.level = 313
AND		p.subject = 'MUSC' AND p.level = 201)
OR		(c.subject = 'MUSC' AND c.level = 314
AND		p.subject = 'MUSC' AND p.level = 313)
OR		(c.subject = 'MUSC' AND c.level = 326
AND		p.subject = 'MUSC' AND p.level = 212)
OR		(c.subject = 'MUSC' AND c.level = 327
AND		p.subject = 'MUSC' AND p.level = 326)
OR		(c.subject = 'MUSC' AND c.level = 335
AND		p.subject = 'MUSC' AND p.level = 235)
OR		(c.subject = 'MUSC' AND c.level = 336
AND		p.subject = 'MUSC' AND p.level = 335)
OR		(c.subject = 'MUSC' AND c.level = 341
AND		p.subject = 'MUSC' AND p.level = 101)
OR		(c.subject = 'MUSC' AND c.level = 344
AND		p.subject = 'MUSC' AND p.level = 214)
OR		(c.subject = 'MUSC' AND c.level = 345
AND		p.subject = 'MUSC' AND p.level = 100)
OR		(c.subject = 'MUSC' AND c.level = 348
AND		p.subject = 'MUSC' AND p.level = 244)
OR		(c.subject = 'MUSC' AND c.level = 348
AND		p.subject = 'MUSC' AND p.level = 235)
OR		(c.subject = 'MUSC' AND c.level = 358
AND		p.subject = 'MUSC' AND p.level = 201)
OR		(c.subject = 'MUSC' AND c.level = 358
AND		p.subject = 'MUSC' AND p.level = 244)
OR		(c.subject = 'MUSC' AND c.level = 359
AND		p.subject = 'MUSC' AND p.level = 358)
OR		(c.subject = 'MUSC' AND c.level = 362
AND		p.subject = 'MUSC' AND p.level = 361)
OR		(c.subject = 'MUSC' AND c.level = 364
AND		p.subject = 'MUSC' AND p.level = 263)
OR		(c.subject = 'MUSC' AND c.level = 366
AND		p.subject = 'MUSC' AND p.level = 263)
OR		(c.subject = 'MUSC' AND c.level = 367
AND		p.subject = 'MUSC' AND p.level = 219)
OR		(c.subject = 'MUSC' AND c.level = 368
AND		p.subject = 'MUSC' AND p.level = 201)
OR		(c.subject = 'MUSC' AND c.level = 368
AND		p.subject = 'MUSC' AND p.level = 202)
OR		(c.subject = 'MUSC' AND c.level = 368
AND		p.subject = 'MUSC' AND p.level = 207)
OR		(c.subject = 'MUSC' AND c.level = 368
AND		p.subject = 'MUSC' AND p.level = 208)
OR		(c.subject = 'MUSC' AND c.level = 371
AND		p.subject = 'MUSC' AND p.level = 335)
OR		(c.subject = 'MUSC' AND c.level = 380
AND		p.subject = 'MUSC' AND p.level = 123)
OR		(c.subject = 'MUSC' AND c.level = 380
AND		p.subject = 'MUSC' AND p.level = 124)
OR		(c.subject = 'MUSC' AND c.level = 396
AND		p.subject = 'MUSC' AND p.level = 295)
OR		(c.subject = 'MUSC' AND c.level = 397
AND		p.subject = 'MUSC' AND p.level = 396)
OR		(c.subject = 'MUSC' AND c.level = 415
AND		p.subject = 'MUSC' AND p.level = 313)
OR		(c.subject = 'MUSC' AND c.level = 416
AND		p.subject = 'MUSC' AND p.level = 263)
OR		(c.subject = 'MUSC' AND c.level = 416
AND		p.subject = 'MUSC' AND p.level = 313)
OR		(c.subject = 'MUSC' AND c.level = 417
AND		p.subject = 'MUSC' AND p.level = 327)
OR		(c.subject = 'MUSC' AND c.level = 418
AND		p.subject = 'MUSC' AND p.level = 417)
OR		(c.subject = 'MUSC' AND c.level = 424
AND		p.subject = 'MUSC' AND p.level = 427)
OR		(c.subject = 'MUSC' AND c.level = 426
AND		p.subject = 'MUSC' AND p.level = 263)
OR		(c.subject = 'MUSC' AND c.level = 427
AND		p.subject = 'MUSC' AND p.level = 123)
OR		(c.subject = 'MUSC' AND c.level = 427
AND		p.subject = 'MUSC' AND p.level = 124)
OR		(c.subject = 'MUSC' AND c.level = 431
AND		p.subject = 'MUSC' AND p.level = 313)
OR		(c.subject = 'MUSC' AND c.level = 437
AND		p.subject = 'MUSC' AND p.level = 336)
OR		(c.subject = 'MUSC' AND c.level = 437
AND		p.subject = 'MUSC' AND p.level = 348)
OR		(c.subject = 'MUSC' AND c.level = 437
AND		p.subject = 'MUSC' AND p.level = 371)
OR		(c.subject = 'MUSC' AND c.level = 438
AND		p.subject = 'MUSC' AND p.level = 437)
OR		(c.subject = 'MUSC' AND c.level = 438
AND		p.subject = 'MUSC' AND p.level = 452)
OR		(c.subject = 'MUSC' AND c.level = 438
AND		p.subject = 'MUSC' AND p.level = 472)
OR		(c.subject = 'MUSC' AND c.level = 452
AND		p.subject = 'MUSC' AND p.level = 348)
OR		(c.subject = 'MUSC' AND c.level = 460
AND		p.subject = 'MUSC' AND p.level = 359)
OR		(c.subject = 'MUSC' AND c.level = 461
AND		p.subject = 'MUSC' AND p.level = 460)
OR		(c.subject = 'MUSC' AND c.level = 465
AND		p.subject = 'MUSC' AND p.level = 364)
OR		(c.subject = 'MUSC' AND c.level = 467
AND		p.subject = 'MUSC' AND p.level = 366)
OR		(c.subject = 'MUSC' AND c.level = 468
AND		p.subject = 'MUSC' AND p.level = 263)
OR		(c.subject = 'MUSC' AND c.level = 469
AND		p.subject = 'MUSC' AND p.level = 219)
OR		(c.subject = 'MUSC' AND c.level = 469
AND		p.subject = 'MUSC' AND p.level = 467)
OR		(c.subject = 'MUSC' AND c.level = 472
AND		p.subject = 'MUSC' AND p.level = 348)
OR		(c.subject = 'MUSC' AND c.level = 472
AND		p.subject = 'MUSC' AND p.level = 336)
OR		(c.subject = 'MUSC' AND c.level = 472
AND		p.subject = 'MUSC' AND p.level = 371)
OR		(c.subject = 'MUSC' AND c.level = 473
AND		p.subject = 'MUSC' AND p.level = 472)
OR		(c.subject = 'MUSC' AND c.level = 473
AND		p.subject = 'MUSC' AND p.level = 452)
OR		(c.subject = 'MUSC' AND c.level = 473
AND		p.subject = 'MUSC' AND p.level = 437)
OR		(c.subject = 'MUSC' AND c.level = 474
AND		p.subject = 'MUSC' AND p.level = 417)
OR		(c.subject = 'MUSC' AND c.level = 474
AND		p.subject = 'MUSC' AND p.level = 415)
OR		(c.subject = 'MUSC' AND c.level = 474
AND		p.subject = 'MUSC' AND p.level = 314)
OR		(c.subject = 'MUSC' AND c.level = 476
AND		p.subject = 'MUSC' AND p.level = 361)
OR		(c.subject = 'MUSC' AND c.level = 482
AND		p.subject = 'MUSC' AND p.level = 123)
OR		(c.subject = 'MUSC' AND c.level = 482
AND		p.subject = 'MUSC' AND p.level = 124)
OR		(c.subject = 'MUSC' AND c.level = 498
AND		p.subject = 'MUSC' AND p.level = 397)
OR		(c.subject = 'MUSC' AND c.level = 499
AND		p.subject = 'MUSC' AND p.level = 498)
/* NURS */
OR		(c.subject = 'NURS' AND c.level = 175
AND		p.subject = 'NURS' AND p.level = 170)
OR		(c.subject = 'NURS' AND c.level = 251
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'NURS' AND c.level = 251
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'NURS' AND c.level = 252
AND		p.subject = 'NURS' AND p.level = 175)
OR		(c.subject = 'NURS' AND c.level = 253
AND		p.subject = 'NURS' AND p.level = 251)
OR		(c.subject = 'NURS' AND c.level = 253
AND		p.subject = 'NURS' AND p.level = 252)
OR		(c.subject = 'NURS' AND c.level = 255
AND		p.subject = 'NURS' AND p.level = 253)
OR		(c.subject = 'NURS' AND c.level = 270
AND		p.subject = 'NURS' AND p.level = 175)
OR		(c.subject = 'NURS' AND c.level = 270
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'NURS' AND c.level = 270
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'NURS' AND c.level = 272
AND		p.subject = 'NURS' AND p.level = 175)
OR		(c.subject = 'NURS' AND c.level = 272
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'NURS' AND c.level = 272
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'NURS' AND c.level = 275
AND		p.subject = 'NURS' AND p.level = 252)
OR		(c.subject = 'NURS' AND c.level = 275
AND		p.subject = 'NURS' AND p.level = 270)
OR		(c.subject = 'NURS' AND c.level = 275
AND		p.subject = 'NURS' AND p.level = 272)
OR		(c.subject = 'NURS' AND c.level = 277
AND		p.subject = 'NURS' AND p.level = 275)
OR		(c.subject = 'NURS' AND c.level = 279
AND		p.subject = 'NURS' AND p.level = 252)
OR		(c.subject = 'NURS' AND c.level = 279
AND		p.subject = 'NURS' AND p.level = 270)
OR		(c.subject = 'NURS' AND c.level = 279
AND		p.subject = 'NURS' AND p.level = 272)
OR		(c.subject = 'NURS' AND c.level = 341
AND		p.subject = 'NURS' AND p.level = 277)
OR		(c.subject = 'NURS' AND c.level = 341
AND		p.subject = 'NURS' AND p.level = 279)
OR		(c.subject = 'NURS' AND c.level = 341
AND		p.subject = 'STAT' AND p.level = 114)
OR		(c.subject = 'NURS' AND c.level = 344
AND		p.subject = 'NURS' AND p.level = 277)
OR		(c.subject = 'NURS' AND c.level = 344
AND		p.subject = 'NURS' AND p.level = 279)
OR		(c.subject = 'NURS' AND c.level = 370
AND		p.subject = 'NURS' AND p.level = 277)
OR		(c.subject = 'NURS' AND c.level = 370
AND		p.subject = 'NURS' AND p.level = 279)
OR		(c.subject = 'NURS' AND c.level = 372
AND		p.subject = 'NURS' AND p.level = 277)
OR		(c.subject = 'NURS' AND c.level = 372
AND		p.subject = 'NURS' AND p.level = 279)
OR		(c.subject = 'NURS' AND c.level = 375
AND		p.subject = 'NURS' AND p.level = 344)
OR		(c.subject = 'NURS' AND c.level = 375
AND		p.subject = 'NURS' AND p.level = 370)
OR		(c.subject = 'NURS' AND c.level = 375
AND		p.subject = 'NURS' AND p.level = 372)
OR		(c.subject = 'NURS' AND c.level = 377
AND		p.subject = 'NURS' AND p.level = 344)
OR		(c.subject = 'NURS' AND c.level = 377
AND		p.subject = 'NURS' AND p.level = 370)
OR		(c.subject = 'NURS' AND c.level = 377
AND		p.subject = 'NURS' AND p.level = 372)
OR		(c.subject = 'NURS' AND c.level = 379
AND		p.subject = 'NURS' AND p.level = 344)
OR		(c.subject = 'NURS' AND c.level = 379
AND		p.subject = 'NURS' AND p.level = 370)
OR		(c.subject = 'NURS' AND c.level = 379
AND		p.subject = 'NURS' AND p.level = 372)
OR		(c.subject = 'NURS' AND c.level = 420
AND		p.subject = 'NURS' AND p.level = 375)
OR		(c.subject = 'NURS' AND c.level = 420
AND		p.subject = 'NURS' AND p.level = 377)
OR		(c.subject = 'NURS' AND c.level = 420
AND		p.subject = 'NURS' AND p.level = 379)
OR		(c.subject = 'NURS' AND c.level = 422
AND		p.subject = 'NURS' AND p.level = 375)
OR		(c.subject = 'NURS' AND c.level = 422
AND		p.subject = 'NURS' AND p.level = 377)
OR		(c.subject = 'NURS' AND c.level = 422
AND		p.subject = 'NURS' AND p.level = 379)
OR		(c.subject = 'NURS' AND c.level = 424
AND		p.subject = 'NURS' AND p.level = 375)
OR		(c.subject = 'NURS' AND c.level = 424
AND		p.subject = 'NURS' AND p.level = 377)
OR		(c.subject = 'NURS' AND c.level = 424
AND		p.subject = 'NURS' AND p.level = 379)
OR		(c.subject = 'NURS' AND c.level = 426
AND		p.subject = 'NURS' AND p.level = 375)
OR		(c.subject = 'NURS' AND c.level = 426
AND		p.subject = 'NURS' AND p.level = 377)
OR		(c.subject = 'NURS' AND c.level = 426
AND		p.subject = 'NURS' AND p.level = 379)
OR		(c.subject = 'NURS' AND c.level = 428
AND		p.subject = 'NURS' AND p.level = 375)
OR		(c.subject = 'NURS' AND c.level = 428
AND		p.subject = 'NURS' AND p.level = 377)
OR		(c.subject = 'NURS' AND c.level = 428
AND		p.subject = 'NURS' AND p.level = 379)
OR		(c.subject = 'NURS' AND c.level = 432
AND		p.subject = 'NURS' AND p.level = 375)
OR		(c.subject = 'NURS' AND c.level = 432
AND		p.subject = 'NURS' AND p.level = 377)
OR		(c.subject = 'NURS' AND c.level = 432
AND		p.subject = 'NURS' AND p.level = 379)
OR		(c.subject = 'NURS' AND c.level = 472
AND		p.subject = 'NURS' AND p.level = 344)
OR		(c.subject = 'NURS' AND c.level = 474
AND		p.subject = 'NURS' AND p.level = 375)
OR		(c.subject = 'NURS' AND c.level = 474
AND		p.subject = 'NURS' AND p.level = 377)
OR		(c.subject = 'NURS' AND c.level = 474
AND		p.subject = 'NURS' AND p.level = 379)
OR		(c.subject = 'NURS' AND c.level = 479
AND		p.subject = 'NURS' AND p.level = 472)
OR		(c.subject = 'NURS' AND c.level = 479
AND		p.subject = 'NURS' AND p.level = 474)
OR		(c.subject = 'NURS' AND c.level = 489
AND		p.subject = 'NURS' AND p.level = 479)
/* ORGA */
OR		(c.subject = 'ORGA' AND c.level = 201
AND		p.subject = 'ECON' AND p.level = 102)
/* PHIL */
OR		(c.subject = 'PHIL' AND c.level = 204
AND		p.subject = 'PHIL' AND p.level = 100)
OR		(c.subject = 'PHIL' AND c.level = 220
AND		p.subject = 'PHIL' AND p.level = 210)
OR		(c.subject = 'PHIL' AND c.level = 305
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 330
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 331
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 333
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 341
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 342
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 355
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 365
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 370
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 381
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 383
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 402
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 402
AND		p.subject = 'PHIL' AND p.level = 205)
OR		(c.subject = 'PHIL' AND c.level = 402
AND		p.subject = 'PHIL' AND p.level = 301)
OR		(c.subject = 'PHIL' AND c.level = 403
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 403
AND		p.subject = 'PHIL' AND p.level = 205)
OR		(c.subject = 'PHIL' AND c.level = 403
AND		p.subject = 'PHIL' AND p.level = 301)
OR		(c.subject = 'PHIL' AND c.level = 404
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 404
AND		p.subject = 'PHIL' AND p.level = 205)
OR		(c.subject = 'PHIL' AND c.level = 404
AND		p.subject = 'PHIL' AND p.level = 301)
OR		(c.subject = 'PHIL' AND c.level = 405
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 405
AND		p.subject = 'PHIL' AND p.level = 205)
OR		(c.subject = 'PHIL' AND c.level = 405
AND		p.subject = 'PHIL' AND p.level = 301)
OR		(c.subject = 'PHIL' AND c.level = 444
AND		p.subject = 'PHIL' AND p.level = 204)
OR		(c.subject = 'PHIL' AND c.level = 444
AND		p.subject = 'PHIL' AND p.level = 205)
/* PHYS */
OR		(c.subject = 'PHYS' AND c.level = 126
AND		p.subject = 'PHYS' AND p.level = 124)
OR		(c.subject = 'PHYS' AND c.level = 146
AND		p.subject = 'PHYS' AND p.level = 144)
OR		(c.subject = 'PHYS' AND c.level = 200
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 200
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'PHYS' AND c.level = 208
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 208
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'PHYS' AND c.level = 212
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 224
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 224
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'PHYS' AND c.level = 226
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 226
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'PHYS' AND c.level = 242
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 242
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'PHYS' AND c.level = 244
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 244
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'PHYS' AND c.level = 244
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'PHYS' AND c.level = 250
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 250
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'PHYS' AND c.level = 252
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 252
AND		p.subject = 'MATH' AND p.level = 114)
OR		(c.subject = 'PHYS' AND c.level = 252
AND		p.subject = 'EASC' AND p.level = 101)
OR		(c.subject = 'PHYS' AND c.level = 255
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 261
AND		p.subject = 'PHYS' AND p.level = 126)
OR		(c.subject = 'PHYS' AND c.level = 301
AND		p.subject = 'PHYS' AND p.level = 208)
OR		(c.subject = 'PHYS' AND c.level = 301
AND		p.subject = 'MATH' AND p.level = 115)
OR		(c.subject = 'PHYS' AND c.level = 302
AND		p.subject = 'PHYS' AND p.level = 200)
OR		(c.subject = 'PHYS' AND c.level = 302
AND		p.subject = 'PHYS' AND p.level = 208)
OR		(c.subject = 'PHYS' AND c.level = 301
AND		p.subject = 'MATH' AND p.level = 115)
OR		(c.subject = 'PHYS' AND c.level = 308
AND		p.subject = 'PHYS' AND p.level = 208)
OR		(c.subject = 'PHYS' AND c.level = 308
AND		p.subject = 'MATH' AND p.level = 115)
OR		(c.subject = 'PHYS' AND c.level = 320
AND		p.subject = 'PHYS' AND p.level = 208)
OR		(c.subject = 'PHYS' AND c.level = 320
AND		p.subject = 'MATH' AND p.level = 115)
OR		(c.subject = 'PHYS' AND c.level = 320
AND		p.subject = 'CHEM' AND p.level = 102)
OR		(c.subject = 'PHYS' AND c.level = 324
AND		p.subject = 'PHYS' AND p.level = 224)
OR		(c.subject = 'PHYS' AND c.level = 330
AND		p.subject = 'PHYS' AND p.level = 208)
OR		(c.subject = 'PHYS' AND c.level = 330
AND		p.subject = 'MATH' AND p.level = 115)
OR		(c.subject = 'PHYS' AND c.level = 330
AND		p.subject = 'PHYS' AND p.level = 224)
OR		(c.subject = 'PHYS' AND c.level = 332
AND		p.subject = 'PHYS' AND p.level = 208)
OR		(c.subject = 'PHYS' AND c.level = 332
AND		p.subject = 'MATH' AND p.level = 115)
OR		(c.subject = 'PHYS' AND c.level = 332
AND		p.subject = 'PHYS' AND p.level = 224)
OR		(c.subject = 'PHYS' AND c.level = 372
AND		p.subject = 'PHYS' AND p.level = 208)
OR		(c.subject = 'PHYS' AND c.level = 372
AND		p.subject = 'PHYS' AND p.level = 244)
OR		(c.subject = 'PHYS' AND c.level = 390
AND		p.subject = 'PHYS' AND p.level = 208)
OR		(c.subject = 'PHYS' AND c.level = 390
AND		p.subject = 'PHYS' AND p.level = 244)
/* PSYC */
OR		(c.subject = 'PSYC' AND c.level = 212
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 212
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'PSYC' AND c.level = 212
AND		p.subject = 'STAT' AND p.level = 151)
OR		(c.subject = 'PSYC' AND c.level = 223
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 223
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'PSYC' AND c.level = 233
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 233
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'PSYC' AND c.level = 241
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 241
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'PSYC' AND c.level = 258
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 258
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'PSYC' AND c.level = 267
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 275
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 281
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 301
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 301
AND		p.subject = 'PSYC' AND p.level = 267)
OR		(c.subject = 'PSYC' AND c.level = 306
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 306
AND		p.subject = 'PSYC' AND p.level = 267)
OR		(c.subject = 'PSYC' AND c.level = 307
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 307
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'PSYC' AND c.level = 307
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 307
AND		p.subject = 'PSYC' AND p.level = 267)
OR		(c.subject = 'PSYC' AND c.level = 312
AND		p.subject = 'PSYC' AND p.level = 212)
OR		(c.subject = 'PSYC' AND c.level = 324
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 326
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 328
AND		p.subject = 'PSYC' AND p.level = 233)
OR		(c.subject = 'PSYC' AND c.level = 337
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 337
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'PSYC' AND c.level = 337
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 337
AND		p.subject = 'PSYC' AND p.level = 267)
OR		(c.subject = 'PSYC' AND c.level = 339
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 339
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'PSYC' AND c.level = 339
AND		p.subject = 'PSYC' AND p.level = 233)
OR		(c.subject = 'PSYC' AND c.level = 339
AND		p.subject = 'PSYC' AND p.level = 275)
OR		(c.subject = 'PSYC' AND c.level = 350
AND		p.subject = 'PSYC' AND p.level = 258)
OR		(c.subject = 'PSYC' AND c.level = 351
AND		p.subject = 'PSYC' AND p.level = 212)
OR		(c.subject = 'PSYC' AND c.level = 351
AND		p.subject = 'PSYC' AND p.level = 258)
OR		(c.subject = 'PSYC' AND c.level = 355
AND		p.subject = 'PSYC' AND p.level = 258)
OR		(c.subject = 'PSYC' AND c.level = 358
AND		p.subject = 'PSYC' AND p.level = 212)
OR		(c.subject = 'PSYC' AND c.level = 358
AND		p.subject = 'PSYC' AND p.level = 281)
OR		(c.subject = 'PSYC' AND c.level = 367
AND		p.subject = 'PSYC' AND p.level = 212)
OR		(c.subject = 'PSYC' AND c.level = 367
AND		p.subject = 'PSYC' AND p.level = 267)
OR		(c.subject = 'PSYC' AND c.level = 369
AND		p.subject = 'PSYC' AND p.level = 104)
OR		(c.subject = 'PSYC' AND c.level = 369
AND		p.subject = 'PSYC' AND p.level = 105)
OR		(c.subject = 'PSYC' AND c.level = 369
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 369
AND		p.subject = 'PSYC' AND p.level = 267)
OR		(c.subject = 'PSYC' AND c.level = 370
AND		p.subject = 'PSYC' AND p.level = 306)
OR		(c.subject = 'PSYC' AND c.level = 370
AND		p.subject = 'PSYC' AND p.level = 307)
OR		(c.subject = 'PSYC' AND c.level = 370
AND		p.subject = 'PSYC' AND p.level = 312)
OR		(c.subject = 'PSYC' AND c.level = 370
AND		p.subject = 'PSYC' AND p.level = 324)
OR		(c.subject = 'PSYC' AND c.level = 373
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 373
AND		p.subject = 'PSYC' AND p.level = 267)
OR		(c.subject = 'PSYC' AND c.level = 375
AND		p.subject = 'PSYC' AND p.level = 275)
OR		(c.subject = 'PSYC' AND c.level = 377
AND		p.subject = 'PSYC' AND p.level = 275)
OR		(c.subject = 'PSYC' AND c.level = 385
AND		p.subject = 'PSYC' AND p.level = 281)
OR		(c.subject = 'PSYC' AND c.level = 391
AND		p.subject = 'PSYC' AND p.level = 233)
OR		(c.subject = 'PSYC' AND c.level = 391
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 408
AND		p.subject = 'PSYC' AND p.level = 212)
OR		(c.subject = 'PSYC' AND c.level = 408
AND		p.subject = 'PSYC' AND p.level = 306)
OR		(c.subject = 'PSYC' AND c.level = 408
AND		p.subject = 'PSYC' AND p.level = 307)
OR		(c.subject = 'PSYC' AND c.level = 423
AND		p.subject = 'PSYC' AND p.level = 223)
OR		(c.subject = 'PSYC' AND c.level = 431
AND		p.subject = 'PSYC' AND p.level = 339)
OR		(c.subject = 'PSYC' AND c.level = 431
AND		p.subject = 'STAT' AND p.level = 151)
OR		(c.subject = 'PSYC' AND c.level = 435
AND		p.subject = 'PSYC' AND p.level = 339)
OR		(c.subject = 'PSYC' AND c.level = 437
AND		p.subject = 'PSYC' AND p.level = 337)
OR		(c.subject = 'PSYC' AND c.level = 438
AND		p.subject = 'PSYC' AND p.level = 435)
OR		(c.subject = 'PSYC' AND c.level = 438
AND		p.subject = 'PSYC' AND p.level = 326)
OR		(c.subject = 'PSYC' AND c.level = 438
AND		p.subject = 'PSYC' AND p.level = 377)
OR		(c.subject = 'PSYC' AND c.level = 439
AND		p.subject = 'PSYC' AND p.level = 339)
OR		(c.subject = 'PSYC' AND c.level = 439
AND		p.subject = 'PSYC' AND p.level = 212)
OR		(c.subject = 'PSYC' AND c.level = 449
AND		p.subject = 'PSYC' AND p.level = 212)
OR		(c.subject = 'PSYC' AND c.level = 449
AND		p.subject = 'PSYC' AND p.level = 241)
OR		(c.subject = 'PSYC' AND c.level = 456
AND		p.subject = 'PSYC' AND p.level = 339)
OR		(c.subject = 'PSYC' AND c.level = 467
AND		p.subject = 'PSYC' AND p.level = 212)
OR		(c.subject = 'PSYC' AND c.level = 467
AND		p.subject = 'PSYC' AND p.level = 267)
OR		(c.subject = 'PSYC' AND c.level = 473
AND		p.subject = 'PSYC' AND p.level = 212)
OR		(c.subject = 'PSYC' AND c.level = 473
AND		p.subject = 'PSYC' AND p.level = 373)
OR		(c.subject = 'PSYC' AND c.level = 475
AND		p.subject = 'PSYC' AND p.level = 275)
OR		(c.subject = 'PSYC' AND c.level = 475
AND		p.subject = 'PSYC' AND p.level = 358)
OR		(c.subject = 'PSYC' AND c.level = 475
AND		p.subject = 'PSYC' AND p.level = 367)
OR		(c.subject = 'PSYC' AND c.level = 499
AND		p.subject = 'PSYC' AND p.level = 312)
/* SOCI */
OR		(c.subject = 'SOCI' AND c.level = 201
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 224
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 225
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 232
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 237
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 241
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 251
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 269
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 271
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 290
AND		p.subject = 'SOCI' AND p.level = 100)
OR		(c.subject = 'SOCI' AND c.level = 301
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 303
AND		p.subject = 'SOCI' AND p.level = 225)
OR		(c.subject = 'SOCI' AND c.level = 310
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 315
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 320
AND		p.subject = 'SOCI' AND p.level = 225)
OR		(c.subject = 'SOCI' AND c.level = 321
AND		p.subject = 'SOCI' AND p.level = 225)
OR		(c.subject = 'SOCI' AND c.level = 325
AND		p.subject = 'SOCI' AND p.level = 225)
OR		(c.subject = 'SOCI' AND c.level = 327
AND		p.subject = 'SOCI' AND p.level = 225)
OR		(c.subject = 'SOCI' AND c.level = 329
AND		p.subject = 'SOCI' AND p.level = 225)
OR		(c.subject = 'SOCI' AND c.level = 333
AND		p.subject = 'SOCI' AND p.level = 232)
OR		(c.subject = 'SOCI' AND c.level = 361
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 362
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 363
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 368
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 377
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 387
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 393
AND		p.subject = 'SOCI' AND p.level = 201)
OR		(c.subject = 'SOCI' AND c.level = 400
AND		p.subject = 'SOCI' AND p.level = 301)
OR		(c.subject = 'SOCI' AND c.level = 402
AND		p.subject = 'SOCI' AND p.level = 301)
OR		(c.subject = 'SOCI' AND c.level = 403
AND		p.subject = 'SOCI' AND p.level = 303)
OR		(c.subject = 'SOCI' AND c.level = 416
AND		p.subject = 'SOCI' AND p.level = 310)
OR		(c.subject = 'SOCI' AND c.level = 416
AND		p.subject = 'SOCI' AND p.level = 315)
OR		(c.subject = 'SOCI' AND c.level = 418
AND		p.subject = 'SOCI' AND p.level = 315)
OR		(c.subject = 'SOCI' AND c.level = 421
AND		p.subject = 'SOCI' AND p.level = 327)
OR		(c.subject = 'SOCI' AND c.level = 422
AND		p.subject = 'SOCI' AND p.level = 327)
OR		(c.subject = 'SOCI' AND c.level = 424
AND		p.subject = 'SOCI' AND p.level = 301)
OR		(c.subject = 'SOCI' AND c.level = 424
AND		p.subject = 'SOCI' AND p.level = 224)
OR		(c.subject = 'SOCI' AND c.level = 428
AND		p.subject = 'SOCI' AND p.level = 327)
OR		(c.subject = 'SOCI' AND c.level = 430
AND		p.subject = 'SOCI' AND p.level = 225)
OR		(c.subject = 'SOCI' AND c.level = 430
AND		p.subject = 'SOCI' AND p.level = 301)
OR		(c.subject = 'SOCI' AND c.level = 449
AND		p.subject = 'SOCI' AND p.level = 301)
OR		(c.subject = 'SOCI' AND c.level = 449
AND		p.subject = 'SOCI' AND p.level = 241)
OR		(c.subject = 'SOCI' AND c.level = 463
AND		p.subject = 'SOCI' AND p.level = 301)
OR		(c.subject = 'SOCI' AND c.level = 470
AND		p.subject = 'SOCI' AND p.level = 301)
OR		(c.subject = 'SOCI' AND c.level = 470
AND		p.subject = 'SOCI' AND p.level = 271)
OR		(c.subject = 'SOCI' AND c.level = 477
AND		p.subject = 'SOCI' AND p.level = 377)
OR		(c.subject = 'SOCI' AND c.level = 496
AND		p.subject = 'SOCI' AND p.level = 315)
OR		(c.subject = 'SOCI' AND c.level = 497
AND		p.subject = 'SOCI' AND p.level = 315)
/* STAT */
OR		(c.subject = 'STAT' AND c.level = 252
AND		p.subject = 'STAT' AND p.level = 151)
OR		(c.subject = 'STAT' AND c.level = 265
AND		p.subject = 'MATH' AND p.level = 115)
OR		(c.subject = 'STAT' AND c.level = 266
AND		p.subject = 'STAT' AND p.level = 265)
OR		(c.subject = 'STAT' AND c.level = 322
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'STAT' AND c.level = 322
AND		p.subject = 'STAT' AND p.level = 265)
OR		(c.subject = 'STAT' AND c.level = 324
AND		p.subject = 'STAT' AND p.level = 266)
OR		(c.subject = 'STAT' AND c.level = 324
AND		p.subject = 'CMPT' AND p.level = 101)
OR		(c.subject = 'STAT' AND c.level = 350
AND		p.subject = 'STAT' AND p.level = 265)
OR		(c.subject = 'STAT' AND c.level = 353
AND		p.subject = 'STAT' AND p.level = 266)
OR		(c.subject = 'STAT' AND c.level = 370
AND		p.subject = 'STAT' AND p.level = 266)
OR		(c.subject = 'STAT' AND c.level = 370
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'STAT' AND c.level = 371
AND		p.subject = 'STAT' AND p.level = 252)
OR		(c.subject = 'STAT' AND c.level = 372
AND		p.subject = 'STAT' AND p.level = 265)
OR		(c.subject = 'STAT' AND c.level = 372
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'STAT' AND c.level = 372
AND		p.subject = 'STAT' AND p.level = 151)
OR		(c.subject = 'STAT' AND c.level = 378
AND		p.subject = 'STAT' AND p.level = 266)
OR		(c.subject = 'STAT' AND c.level = 378
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'STAT' AND c.level = 412
AND		p.subject = 'MATH' AND p.level = 120)
OR		(c.subject = 'STAT' AND c.level = 412
AND		p.subject = 'MATH' AND p.level = 214)
OR		(c.subject = 'STAT' AND c.level = 412
AND		p.subject = 'STAT' AND p.level = 266)
OR		(c.subject = 'STAT' AND c.level = 412
AND		p.subject = 'STAT' AND p.level = 322)
OR		(c.subject = 'STAT' AND c.level = 465
AND		p.subject = 'MATH' AND p.level = 225)
OR		(c.subject = 'STAT' AND c.level = 465
AND		p.subject = 'STAT' AND p.level = 266)
OR		(c.subject = 'STAT' AND c.level = 478
AND		p.subject = 'STAT' AND p.level = 266)
OR		(c.subject = 'STAT' AND c.level = 478
AND		p.subject = 'STAT' AND p.level = 378)
OR		(c.subject = 'STAT' AND c.level = 495
AND		p.subject = 'STAT' AND p.level = 322)
OR		(c.subject = 'STAT' AND c.level = 496
AND		p.subject = 'STAT' AND p.level = 322);

-- For 300,400 courses that have no prereqs, add a prereq to it so people can't enroll.
DELETE
FROM course
WHERE id NOT IN (select course from prereq)
and level > 350
and (CAST(subject as nchar(4)) + ' ' + CAST(level as varchar) <> 'MUSC 361');